config/routes.rb
Skillslist::Application.routes.draw do

  root :to => "domains#index"

  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update, :destroy]

  resources :domains do
    resources :skills do
      resources :user_histories
    end
  end

  resources :user_histories

end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
  attr_accessible :date_done, :date_observed, :date_taught, :domain_id, :skill_id, :user_id

  has_many :skills
  has_many :domain, :through => :skills

  accepts_nested_attributes_for :domain
  accepts_nested_attributes_for :skills

end

app/controllers/user_histories_controller.rb
class UserHistoriesController < ApplicationController
  # GET /user_histories
  # GET /user_histories.json
  def index
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_histories = @skill.user_histories

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @user_histories }
    end
  end

  # GET /user_histories/1
  # GET /user_histories/1.json
  def show
    
    @user_history = UserHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user_history }
    end
  end

  # GET /user_histories/new
  # GET /user_histories/new.json
  def new
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_history = @skill.user_histories.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user_history }
    end
  end

  # GET /user_histories/1/edit
  def edit
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_history = @skill.user_histories.find(params[:id])
  end

  # POST /user_histories
  # POST /user_histories.json
  def create
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_history = @skill.user_histories.build(params[:user_history])

    respond_to do |format|
      if @user_history.save
        format.html { redirect_to domain_skill_path(@domain, @skill), notice: 'User history was successfully created.' }
        format.json { render json: @user_history, status: :created, location: @user_history }
      else
        format.html { render action: "new" }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /user_histories/1
  # PUT /user_histories/1.json
  def update
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_history = UserHistory.find(params[:id])

    respond_to do |format|
      if @user_history.update_attributes(params[:user_history])
        format.html { redirect_to domain_skill_path(@domain, @skill), notice: 'User history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_histories/1
  # DELETE /user_histories/1.json
  def destroy
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:skill_id])
    @user_history = UserHistory.find(params[:id])
    @user_history.destroy

    respond_to do |format|
      format.html { redirect_to user_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/user_histories_helper.rb
module UserHistoriesHelper
end

app/views/user_histories/_form.html.erb
<%= simple_form_for([@domain, @skill, @user_history]) do |f| %>
  <%= f.error_notification %>

  <p><b>Domain:</b> <%= @domain.name %></p>
  <p><b>Skill:</b> <%= @skill.name %></p>
  <p>&nbsp;</p>

  <div class="form-inputs">
    <%= f.input :date_observed, :as => :date, :include_blank => true %>
    <%= f.input :date_done, :as => :date, :include_blank => true %>
    <%= f.input :date_taught, :as => :date, :include_blank => true %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :domain_id, :value => @domain.id %>
    <%= f.hidden_field :skill_id, :value => @skill.id %>
    <%= f.button :submit, 'Save Dates' %>
  </div>
<% end %>

app/views/user_histories/edit.html.erb
<h3>Update Skill: <%= @skill.name %></h3>

<%= render 'form' %>

<%= link_to 'Back to skill page', domain_skill_path(@domain, @skill) %>

app/views/user_histories/index.html.erb
<h3>List of Skill Dates</h3>

<table class="table">
  <tr>
    <th>User</th>
    <th>Domain</th>
    <th>Skill</th>
    <th>Date observed</th>
    <th>Date done</th>
    <th>Date taught</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_histories.each do |user_history| %>
  <tr>
    <td><%= user_history.user_id %></td>
    <td><%= user_history.domain_id %></td>
    <td><%= user_history.skill_id %></td>
    <td><%= user_history.date_observed %></td>
    <td><%= user_history.date_done %></td>
    <td><%= user_history.date_taught %></td>
    <td><%= link_to 'Show', user_history %></td>
    <td><%= link_to 'Edit', edit_user_history_path(user_history) %></td>
    <td><%= link_to 'Destroy', user_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User history', new_user_history_path %>

app/views/user_histories/new.html.erb
<h3>Update Skill: <%= @skill.name %></h3>

<%= render 'form' %>

<%= link_to 'Back to skill page', domain_skill_path(@domain, @skill) %>

app/views/user_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_history.user_id %>
</p>

<p>
  <b>Domain:</b>
  <%= @user_history.domain_id %>
</p>

<p>
  <b>Skill:</b>
  <%= @user_history.skill_id %>
</p>

<p>
  <b>Date observed:</b>
  <%= @user_history.date_observed %>
</p>

<p>
  <b>Date done:</b>
  <%= @user_history.date_done %>
</p>

<p>
  <b>Date taught:</b>
  <%= @user_history.date_taught %>
</p>


<%= link_to 'Edit', edit_user_history_path(@user_history) %> |
<%= link_to 'Back', user_histories_path %>