config/routes.rb
Skillslist::Application.routes.draw do

  root :to => "domains#index"

  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update, :destroy]

  resources :domains do
    resources :skills do
      resources :user_histories
    end
  end

  resources :user_histories

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessor :password_confirmation, :current_password
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first, :last, :role
  # attr_accessible :title, :body

 def name
 	self.first + ' ' + self.last
 end

 ROLES = %w[intern resident]
 FULLROLES = %w[admin intern resident]

 has_one :domain
 has_many :skills, :through => :domain

 accepts_nested_attributes_for :domain,
    :reject_if => :all_blank,
    :allow_destroy => true
 accepts_nested_attributes_for :skills
 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
    	@users = User.all

    	respond_to do |format|
      	format.html # index.html.erb
      	format.json { render json: @user }
    	end
  	end

	def show

    if params[:id].nil? # if there is no user id in params, show current one
    @user = current_user
     # if there is the user id in params just use it, 
     # maybe get 'authorization failed'
    else
      @user = User.find(params[:id])
    end

		
    @user_history = UserHistory.where(:user_id => @user.id)
  
  

		respond_to do |format|
           format.html # show.html.erb
           format.json { render json: @user }
    	end
	end

  def edit

    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    successfully_updated = if @user.email != params[:user][:email] ||
      !params[:user][:password].blank? 
      @user.update_with_password(params[:user])
    else
      # remove the virtual current_password attribute update_without_password
      # doesn't know how to ignore it
      params[:user].delete(:current_password)
      @user.update_without_password(params[:user])
    end

    if successfully_updated
      
      # Sign in the user bypassing validation in case his password changed
     
      redirect_to user_url
    else
      render "edit"
    end
    
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h4>Edit <%= @user.first %> <%= @user.last %></h4>

<%= simple_form_for(@user, :html => {:class => 'form-vertical' }) do |f| %>
  <%= f.input :first %>
  <%= f.input :last %>
  <% if current_user.role == "admin" %>
    <%= f.input :role, collection: User::FULLROLES %>
  <% else %>
    <%= f.input :role, collection: User::ROLES %>
  <% end %>
  <%= f.input :email, placeholder: 'user@domain.com' %>
  <%= f.input :password, hint: '(leave blank if you don\'t want to change it)' %>
  <%= f.input :password_confirmation %>
  <%= f.input :current_password, hint: 'Type your current password to verify changes' %>
  <%= f.button :submit %>
<% end %>

<h4>Cancel my account</h4>

<p>Unhappy? <%= button_to "Cancel my account", user_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

<%= link_to "Back", :back %>

app/views/users/index.html.erb
<h3>List of Users</h3>

<table class="user-list table">
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Type</th>
    <th>Email</th>
    <th>Last Visit</th>
    <th><th>
    <% if current_user.role == "admin" %>
    <th><th>
    <th><th>
        <% else %>
    <% end %>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first %></td>
    <td><%= user.last %></td>
    <td><%= user.role %></td>
    <td><%= user.email %></td>
    <td><%= user.last_sign_in_at %></td>
    <% if current_user.role == "admin" %>
    <td><% if can? :read, User %><%= link_to 'Show', user %><% end %></td>
    <td><% if can? :update, User %><%= link_to 'Edit', edit_user_path(user) %><% end %></td>
    <td><% if can? :destroy, User %><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %><% end %></td>
    <% else %>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/users/show.html.erb
<h3><%= @user.first %> <%= @user.last %>'s Profile</h3>
<% if current_user.id == @user.id %>
<% if can? :update, User %><%= link_to 'Edit Profile', edit_user_path %><% end %>
<% if can? :destroy, User %> | <%= link_to 'Cancel my account', registration_path(@user), :data => { :confirm => "Are you sure?" }, :method => :delete %><% end %>
<% end %>

<p>&nbsp;</p>
<p><b>Email:</b> <%= @user.email %></p>
<p><b>Level:</b> <%= @user.role %></p>
<p><b>Last Sign In:</b> <%= @user.last_sign_in_at.localtime %></p>
<p>&nbsp;</p>


<!-- Show what skills are yet to be attempted -->
<h4>Skills Record</h4>
<% @domains = Domain.all %>
  <% @domains.each do |domain| %>
  <p>Curriculum: <%= domain.curriculum %></p>
<table class="table">
  <tr>
    <th>Domain</th>
    <th>Skill <em>(click to update dates)</em><th>
    <th>Observed</th>
    <th>Done</th>
    <th>Taught</th>
  </tr>
  
    <% @skills = domain.skills %>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= link_to skill.name, domain_skill_path(domain, skill) %></td>
        <% if @user_history = UserHistory.where(:user_id => @user.id, :skill_id => skill.id).any? %>
        <% @user_history = UserHistory.where(:user_id => @user.id, :skill_id => skill.id) %>
        <% user_history = @user_history[0] %>
        <td></td>
        <td><%= user_history.date_observed %></td>
        <td><%= user_history.date_done %></td>
        <td><%= user_history.date_taught %></td>
        <% else %>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <% end %>
      </tr> 
    <% end %>
  
</table>
<% end %>