config/routes.rb
Skillslist::Application.routes.draw do

  root :to => "domains#index"

  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update, :destroy]

  resources :domains do
    resources :skills do
      resources :user_histories
    end
  end

  resources :user_histories

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name, :observed, :performed, :standard, :taught
  belongs_to :domain
  has_many :users, :through => :domain
 
  has_many :user_histories
 

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @domain = Domain.find(params[:domain_id])
    @skills = @domain.skills

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.build(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to domain_skill_url(@domain, @skill), notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to domain_skill_url(@domain, @skill), notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @domain = Domain.find(params[:domain_id])
    @skill = @domain.skills.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to domain_skills_url(@domain) }
      format.json { head :no_content }
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for([@domain, @skill]) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :standard %><br />
    <%= f.text_area :standard %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h3>Edit Skill: <%= @skill.name %></h3>

<%= render 'form' %>

<%= link_to 'Cancel Update', domain_skill_path(@domain, @skill) %>

app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Standard</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.name %></td>
    <td><%= skill.standard %></td>

    <td><%= link_to 'Show', domain_skill_path(@domain, skill) %></td>
    <td><%= link_to 'Edit', edit_domain_skill_path(@domain, skill) %></td>
    <td><%= link_to 'Destroy', domain_skill_path(@domain, skill), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skill', new_domain_skill_path(@domain) %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', domain_skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>



<h3>Skill:
  <%= @skill.name %>
</h3>



<%= link_to 'Edit Skill', edit_domain_skill_path(@domain, @skill) %> |
<% dname = @domain.name %><%= link_to "Back to #{ dname } Domain", @domain %>
<p>&nbsp;</p>

<p>
  <b>Domain:</b> <%= @domain.name %>
</p>

<p>
  <b>Skill Standard:</b>
  <%= @skill.standard %>
</p>
<p>&nbsp;</p>

<!-- Show if there is a user_history for this user and this skill -->
<% if UserHistory.where(:user_id => current_user.id, :skill_id => @skill.id).any? %>
<% @user_history = UserHistory.where(:user_id => current_user.id, :skill_id => @skill.id) %>
<% @user_hist = @user_history[0] %>
<p>
  <b>Date Observed:</b>
  <% if @user_hist.date_observed %>
  <%= @user_hist.date_observed %>
  <% else %>
  Yet to observe
  <% end %>
</p>

<p>
  <b>Date Performed:</b>
  <% if @user_hist.date_done %>
  <%= @user_hist.date_done %>
  <% else %>
  Yet to do
  <% end %>
</p>

<p>
  <b>Date Taught:</b>
  <% if @user_hist.date_taught %>
  <%= @user_hist.date_taught %>
  <% else %>
  Yet to teach
  <% end %>
</p>
<% else %>

<% end %>

<p>&nbsp;</p>

<% if UserHistory.where(:user_id => current_user.id, :skill_id => @skill.id).any? %>
<% @user_history = UserHistory.where(:user_id => current_user.id, :skill_id => @skill.id) %>
<% @user_hist = @user_history[0] %>
<% if @user_hist.date_observed || @user_hist.date_done || @user_hist.date_taught %>
<%= link_to 'Update Dates', { :controller => :user_histories, :action => :edit, :id => @user_hist.id, :domain_id => @user_hist.domain_id, :skill_id => @user_hist.skill_id } %>
<% end %>
<% else %>
<%= link_to 'Add Achievement Dates', new_domain_skill_user_history_path(@domain, @skill) %>
<% end %>