config/routes.rb
Skillslist::Application.routes.draw do

  root :to => "domains#index"

  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update, :destroy]

  resources :domains do
    resources :skills do
      resources :user_histories
    end
  end

  resources :user_histories

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  attr_accessible :curriculum, :name, :stream
  belongs_to :user
  has_many :skills
  has_many :user_histories, :through => :skills


  accepts_nested_attributes_for :skills,
  	:reject_if => :all_blank


end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_filter :authenticate_user!
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @domains }
    end
  end

  # GET /domains/1
  # GET /domains/1.json
  def show
    @domain = Domain.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/new
  # GET /domains/new.json
  def new
    @domain = Domain.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @domain }
    end
  end

  # GET /domains/1/edit
  def edit
    @domain = Domain.find(params[:id])
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(params[:domain])

    respond_to do |format|
      if @domain.save
        format.html { redirect_to @domain, notice: 'Domain was successfully created.' }
        format.json { render json: @domain, status: :created, location: @domain }
      else
        format.html { render action: "new" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /domains/1
  # PUT /domains/1.json
  def update
    @domain = Domain.find(params[:id])

    respond_to do |format|
      if @domain.update_attributes(params[:domain])
        format.html { redirect_to @domain, notice: 'Domain was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain = Domain.find(params[:id])
    @domain.destroy

    respond_to do |format|
      format.html { redirect_to domains_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :curriculum %><br />
    <%= f.text_field :curriculum %>
  </div>
  <div class="field">
    <%= f.label :stream %><br />
    <%= f.text_field :stream %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/edit.html.erb
<h3>Edit the <%= @domain.name %> Domain</h3>

<%= render 'form' %>

<%= link_to 'Cancel Update', @domain %> |
<%= link_to 'Back to list of Domains', domains_path %>

app/views/domains/index.html.erb
<h3>List of Domains</h3>
<%= link_to 'Add A New Domain', new_domain_path %>
<p>&nbsp;</p>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Curriculum</th>
    <th>Stream</th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |domain| %>
  <tr>
    <td><%= link_to domain.name, domain %></td>
    <td><%= domain.curriculum %></td>
    <td><%= domain.stream %></td>
    <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
    <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/domains/new.html.erb
<h1>New domain</h1>

<%= render 'form' %>

<%= link_to 'Back', domains_path %>

app/views/domains/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Domain:
  <%= @domain.name %></h3>
<%= link_to 'Edit this Domain', edit_domain_path(@domain) %> |
<%= link_to 'Show The List of Domains', domains_path %> |
<%= link_to 'Add A New Skill To This Domain', new_domain_skill_path(@domain) %>
<p>&nbsp;</p>

<p>
  <b>Curriculum:</b>
  <%= @domain.curriculum %>
</p>

<p>
  <b>Stream:</b>
  <%= @domain.stream %>
</p>

<!-- List Skills -->
<p><b>Skills In This Domain:</b></p>
<% @domain.skills.each do |skill| %>
	<%= link_to skill.name, domain_skill_path(@domain, skill) %><br />
	<% end %>
<p>&nbsp;</p>	